# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drone_control.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(664, 466)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 30, 381, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setmode = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.setmode.setObjectName("setmode")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.setmode.addItem("")
        self.horizontalLayout.addWidget(self.setmode)
        self.arm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.arm.setObjectName("arm")
        self.horizontalLayout.addWidget(self.arm)
        self.disarm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.disarm.setObjectName("disarm")
        self.horizontalLayout.addWidget(self.disarm)
        self.takeoff = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.takeoff.setObjectName("takeoff")
        self.horizontalLayout.addWidget(self.takeoff)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 80, 381, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_speed = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.edit_speed.setObjectName("edit_speed")
        self.horizontalLayout_2.addWidget(self.edit_speed)
        self.change_speed = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.change_speed.setObjectName("change_speed")
        self.horizontalLayout_2.addWidget(self.change_speed)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 160, 381, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_lat = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.edit_lat.setObjectName("edit_lat")
        self.horizontalLayout_3.addWidget(self.edit_lat)
        self.edit_lng = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.edit_lng.setObjectName("edit_lng")
        self.horizontalLayout_3.addWidget(self.edit_lng)
        self.edit_alt = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.edit_alt.setObjectName("edit_alt")
        self.horizontalLayout_3.addWidget(self.edit_alt)
        self.go = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.go.setObjectName("go")
        self.horizontalLayout_3.addWidget(self.go)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(140, 120, 381, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edit_yaw = QtWidgets.QTextEdit(self.horizontalLayoutWidget_4)
        self.edit_yaw.setObjectName("edit_yaw")
        self.horizontalLayout_4.addWidget(self.edit_yaw)
        self.change_yaw = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.change_yaw.setObjectName("change_yaw")
        self.horizontalLayout_4.addWidget(self.change_yaw)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 200, 541, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.display_timestamp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_timestamp.setText("")
        self.display_timestamp.setObjectName("display_timestamp")
        self.gridLayout.addWidget(self.display_timestamp, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 1)
        self.display_speed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_speed.setText("")
        self.display_speed.setObjectName("display_speed")
        self.gridLayout.addWidget(self.display_speed, 8, 1, 1, 1)
        self.display_gps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_gps.setText("")
        self.display_gps.setObjectName("display_gps")
        self.gridLayout.addWidget(self.display_gps, 10, 1, 1, 1)
        self.display_flightmode = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_flightmode.setText("")
        self.display_flightmode.setObjectName("display_flightmode")
        self.gridLayout.addWidget(self.display_flightmode, 1, 1, 1, 1)
        self.display_altitude = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_altitude.setText("")
        self.display_altitude.setObjectName("display_altitude")
        self.gridLayout.addWidget(self.display_altitude, 9, 1, 1, 1)
        self.display_location = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_location.setText("")
        self.display_location.setObjectName("display_location")
        self.gridLayout.addWidget(self.display_location, 3, 1, 1, 1)
        self.display_battery = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_battery.setText("")
        self.display_battery.setObjectName("display_battery")
        self.gridLayout.addWidget(self.display_battery, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.display_isarmed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_isarmed.setText("")
        self.display_isarmed.setObjectName("display_isarmed")
        self.gridLayout.addWidget(self.display_isarmed, 2, 1, 1, 1)
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.edit_lat.raise_()
        self.gridLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.setmode.setItemText(0, _translate("Form", "STABILIZE"))
        self.setmode.setItemText(1, _translate("Form", "ACRO"))
        self.setmode.setItemText(2, _translate("Form", "ALT_HOLD"))
        self.setmode.setItemText(3, _translate("Form", "AUTO"))
        self.setmode.setItemText(4, _translate("Form", "GUIDED"))
        self.setmode.setItemText(5, _translate("Form", "LOITER"))
        self.setmode.setItemText(6, _translate("Form", "RTL"))
        self.setmode.setItemText(7, _translate("Form", "CIRCLE"))
        self.setmode.setItemText(8, _translate("Form", "POSITION"))
        self.setmode.setItemText(9, _translate("Form", "LAND"))
        self.arm.setText(_translate("Form", "ARM"))
        self.disarm.setText(_translate("Form", "DISARM"))
        self.takeoff.setText(_translate("Form", "TAKEOFF"))
        self.change_speed.setText(_translate("Form", "CHANGE SPEED"))
        self.go.setText(_translate("Form", "GOTO"))
        self.change_yaw.setText(_translate("Form", "CHANGE YAW"))
        self.label.setText(_translate("Form", "Timestamp :"))
        self.label_5.setText(_translate("Form", "Speed :"))
        self.label_4.setText(_translate("Form", "Battery :"))
        self.label_3.setText(_translate("Form", "Attitude :"))
        self.label_2.setText(_translate("Form", "Location :"))
        self.label_7.setText(_translate("Form", "Flight Mode :"))
        self.label_6.setText(_translate("Form", "GPS_Status :"))
        self.label_8.setText(_translate("Form", "isArmed :"))

